import {BsThreeDotsVertical} from 'react-icons/bs'
const data = [
    {
      id: '1',
      user:"user 1",
      city:"city 1",
      phone:"phone 1",
      timeZone:"Time Zone  1",
      button:<BsThreeDotsVertical/>,
      email: 'Sincere@april.biz',
    },
    {
        id: '2',
        user:"user 2",
        city:"city 2",
      phone:"phone 2",
      timeZone:"Time Zone 2",
      button:<BsThreeDotsVertical/>,
      email: 'Shanna@melissa.tv'
    },
    {
        id: '3',
        city:"city 3",
        user:"user 3",
      phone:"phone 3",
      timeZone:"Time Zone 3",
      button:<BsThreeDotsVertical/>,
        email: 'Nathan@yesenia.net',
      },
      {
        id: '4',
        user:"user 4",
        city:"city 4",
      phone:"phone 4",
      timeZone:"Time Zone 4",
      button:<BsThreeDotsVertical/>,
        email: 'Julianne.OConner@kory.org',
      },
      {
        id: '5',
        user:"user 5",
        city:"city 5",
      phone:"phone 5",
      timeZone:"Time Zone 5",
      button:<BsThreeDotsVertical/>,
        email: 'Lucio_Hettinger@annie.ca',
      },
      {
        id: '6',
        user:"user 6",
        city:"city 6",
      phone:"phone 6",
      timeZone:"Time Zone 6",
      button:<BsThreeDotsVertical/>,
        email: 'Karley_Dach@jasper.info',
      },
      {
        id: '7',
        user:"user 7",
        city:"city 7",
      phone:"phone 7",
      timeZone:"Time Zone 7",
      button:<BsThreeDotsVertical/>,
        email: 'Telly.Hoeger@billy.biz',
      },
      {
        id: '8',
        city:"city 8",
        user:"user 8",
      phone:"phone 8",
      timeZone:"Time Zone 8",
      button:<BsThreeDotsVertical/>,
        email: 'Sherwood@rosamond.me',
      },
      {
        id: '9',
        user:"user 9",
        city:"city 9",
      phone:"phone 9",
      timeZone:"Time Zone 9",
      button:<BsThreeDotsVertical/>,
        email: 'Chaim_McDermott@dana.io',
      },
      {
        id: '10',
        user:"user 10",
        city:"city 10",
      phone:"phone 10",
      timeZone:"Time Zone 10",
      button:<BsThreeDotsVertical/>,
        email: 'Rey.Padberg@karina.biz',
      },
    // Add more data as needed
  ];
  export default data;